language: python
sudo: false
branches:
  only:
  - master
  - /^dev.*$/
python:
- '3.6'
install:
- pip install --upgrade setuptools
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update conda
- conda install tornado=5.1.1
- conda info -a
- conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f requirements.txt
- source activate test-environment
before_script:
  flake8 .
script:
- py.test adam --cov=adam --ignore=adam/tests/integration_tests/hypercube_test.py
after_success:
- coveralls
before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- openssl aes-256-cbc -K $encrypted_3633a9d4c228_key -iv $encrypted_3633a9d4c228_iv
  -in test_config.json.enc -out test_config.json -d
